### ISSUE TITLE
I.Assert nor I.Expect fail tests using PageObject in v3 with NUnit

### ISSUE THREAD

**Issue by robinbihun** [stirno/FluentAutomation#104]
Given the following test:
![image](https://cloud.githubusercontent.com/assets/138997/2700100/4ebb0fe2-c40f-11e3-88d3-839e061a238f.png)
and the following snippet from my PageObject<LoginPage>
![image](https://cloud.githubusercontent.com/assets/138997/2700113/72443ae2-c40f-11e3-833a-b92e19fe64b5.png)
It should fail the test because of the .Class("input-validation-error2") class does not exist on the object tested; however, using I.Assert and I.Expect with either Config.ExpectIsAssert set to true or false. I get the following in the log, but the test is marked as "Passed." (using NUnit)
![image](https://cloud.githubusercontent.com/assets/138997/2700142/b0ef94d0-c40f-11e3-981a-a3e9c728c3d9.png)

The documentation says: "when Settings.ExpectIsAssert is set to false, Assert will throw an Exception and fail a test."

This does not appear to be happening in Version 3

**Comment by stirno** [comment]
bug report with pictures and all supporting details!!!! perfect!

On it, Thanks for the report!

**Comment by stirno** [comment]
Sorry for the delay looking into this, crazy few weeks.

First problem, the docs: They are a bit unclear and possibly just wrong on the actual behavior of the ExpectIsAssert flag. In all cases, I.Assert.\* will throw an exception. The flag only affects the behavior of the I.Expect.\* commands -- basically the ability to have legacy expects throw exceptions to fail tests.

In 3.0 ExpectIsAssert is defaulted to false, but that should have no effect on the sample test in the images you provided.

With the following test:

``` csharp
[Test]
public void TestBugReport()
{
    I
        .Open("http://google.com")
        .Assert.Class("wowza").On("input[type='text']");
}
```

I get a consistent, proper failure in NUnit.

```
Test Outcome:   Failed
Test Duration:  0:00:09.169

Result Message: FluentAutomation.Exceptions.FluentException : Waited [5000ms] for action: Expected element [input[type='text']] to include CSS class [wowza] but current class attribute is [gbqfif].
```

Can you provide a test against a public site that isn't failing properly? Would be super helpful for repro purposes. Thanks!

**Comment by robinbihun** [comment]
Maybe i'm doing something wrong, but i would expect this to work...

```
[TestFixture]
public class GoogleTest : FluentTest
{
    public GoogleTest()
    {
        // Testing 3 major browsers.
        SeleniumWebDriver.Bootstrap(
            SeleniumWebDriver.Browser.Chrome, 
            SeleniumWebDriver.Browser.InternetExplorer,
            SeleniumWebDriver.Browser.Firefox);
    }

    [Test]
    public void CanFindSearchBox()
    {
        new SearchPage(this)
            .Go()
            .AssertSearchHasClass("wowsa");
    }
}

public class SearchPage : PageObject<SearchPage>
{
    public SearchPage(FluentTest test)
        : base(test)
    {
        Url = "http://www.google.com";
    }

    public SearchPage AssertSearchHasClass(string cssClass)
    {
        I.Assert.Class(cssClass).On("input[type='text']");

        return this;
    }
}
```

With the following Packages.config file:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FluentAutomation.Core" version="3.0.0-beta" targetFramework="net451" />
  <package id="FluentAutomation.SeleniumWebDriver" version="3.0.0-beta" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="5.0.5" targetFramework="net451" />
  <package id="NUnit" version="2.6.3" targetFramework="net451" />
  <package id="Selenium.Support" version="2.41.0" targetFramework="net451" />
  <package id="Selenium.WebDriver" version="2.41.0" targetFramework="net451" />
</packages>
```

I get the following when running the test
![image](https://cloud.githubusercontent.com/assets/138997/2831998/c483b9c0-cfbf-11e3-9af1-804244ae1bcb.png)

**Comment by stirno** [comment]
Beautiful details once again. Looks like our problem lies in the Multi-browser execution. With a single browser (as I tested it), it works as expected.. Multiple browsers its eating the exception. On it!

**Comment by stirno** [comment]
Once I looked closely, the issue was pretty obvious.. Thanks for reporting and following up quickly! Fixed in our dev branch, should make it to NuGet this weekend I hope.
