### ISSUE TITLE
Pass the "CommandTimeout" parameter to SeleniumWebDriver.Bootstrap

### ISSUE THREAD

**Issue by ubous** [stirno/FluentAutomation#105]
I need to increase the timeout of HttpWebRequest.GetResponse through SeleniumWebDriver but I can't and it is always at 60 seconds. The RemoteWebDriver has a constructor that takes as a parameter a "commandTimeout". It would be nice to have this option in one of the overloads to SeleniumWebDriver.Bootstrap.

Thanks!

**Comment by stirno** [comment]
In dev, will be on NuGet with v3.0 -- all the bootstrap versions now have an overload accepting the command timeout.

Thanks!
