### ISSUE TITLE
The browser does not go / stay at full screen

### ISSUE THREAD

**Issue by brijeshbharadwaj** [stirno/FluentAutomation#109]
The browser does not seem to start tests in full screen (not F11 equivalent, i mean occupying all available area).

Even if i use WebDriver.Manage().Window.Maximize(); to maximize it, it gets restored to a smaller size almost immediately (maybe on next fluent action?).

**Comment by stirno** [comment]
Ya, we kind of 'took' control of the window to allow for scoped window resizing in the WithConfig blocks so every access of the `I` property checks to see if something happened and resets it.

This is somewhat critical to some other behaviors so it might be best to add a Maximized window option to settings to solve this. I'll think about it and get something checked in.

Thanks for the report!

**Comment by stirno** [comment]
Added WindowMaximized option to handle this scenario: https://github.com/stirno/FluentAutomation/commit/a699adafe7549a9552d9723afeccd5f34caa66ef

Available in dev branch now, NuGet with the 3.0 release.
