### ISSUE TITLE
I.Assert.Count() not working when no item

### ISSUE THREAD

**Issue by jbblanchet** [stirno/FluentAutomation#110]
`I.Assert.Count` passes when the selector return nothing, even if you're expecting an item.

So `I.Assert.Count(1).Of("#dummy")` passes even if no element with an id of dummy is present in the page.

I suspect the try/catch in the Count method to be responsible for eating the exception, but I haven't had time to test my theory yet.

**Comment by stirno** [comment]
That seems less than ideal... ;) You're suspicion is likely accurate. @pauljz or I can take a look tomorrow I hope. Thanks!

**Comment by stirno** [comment]
Fixed by b5aaf87701af2fc9f7ae614ec1b1a752a0441b76
