### ISSUE TITLE
Using NUnit, setting multiple SeleiniumWebDriver.Bootstrap browsers does not work inside a single TestFixture

### ISSUE THREAD

**Issue by dmcquiston** [stirno/FluentAutomation#112]
Goal: Write one test run in multiple browsers.

Using the PageObject<> model, in order to test multiple browsers, no matter what I tried, I had to separate out the different browser tests for the same test code into separate sub-classes (TestFixture).

My PageObject assertions are doing simple checks for certain elements, nothing crazy. The following are my page object classes:

```
public class LoginPage : PageObject<LoginPage>
{
    public LoginPage(FluentTest test)
        : base(test)
    {
        Url = "myloginurl";
        At = () => I.Assert.Exists(SearchInput);
    }

    public PortalPage LoginSuccess(string userName, string password)
    {
        Login(userName, password);
        return this.Switch<PortalPage>();
    }

    private void Login(string userName, string password)
    {
        I.Enter(userName).In("input[name=USER]");
        I.Enter(password).In("input[name=PASSWORD]");
        I.Press("{ENTER}");
    }

    private const string SearchInput = "form[id='frmDefault']";
}

public class PortalPage : PageObject<PortalPage>
{
    public PortalPage(FluentTest test)
        : base(test)
    {
        At = () => I.Assert.Exists(PortalPageHeader);
    }

    public PortalPage ValidateLoggedIn(string name)
    {
        I.Assert.Text(t => t.Contains(name)).In(PortalPageHeader);
        return this;
    }

    private const string PortalPageHeader = "div[id='siteHeading']";
}
```

The following are my actual unit tests:

```
public class LoginTests : FluentTest
{
    public void LoginSuccess(string userName, string password)
    {
        new LoginPage(this)
            .Go()
            .LoginSuccess(userName, password)
            .ValidateLoggedIn("Logged in");
    }

    public void LoginSuccess()
    {
        LoginSuccess(GlobalSettings.Id, GlobalSettings.Password);
    }
}

[TestFixture]
public class ChromeLoginTests : LoginTests
{
    [Test]
    public void ChromeLoginTest()
    {
        SeleniumWebDriver.Bootstrap(Browser.Chrome);
        LoginSuccess();
    }
}

[TestFixture]
public class FirefoxLoginTests : LoginTests
{
    [Test]
    public void FirefoxLoginTest()
    {
        SeleniumWebDriver.Bootstrap(Browser.Firefox);
        LoginSuccess();
    }
}

[TestFixture]
public class InternetExplorerLoginTests : LoginTests
{
    [Test]
    public void InternetExplorerLoginTest()
    {
        SeleniumWebDriver.Bootstrap(Browser.InternetExplorer);
        LoginSuccess();
    }
}
```

If you need any additional details, I would be more than happy to provide them. Thanks.

**Comment by stirno** [comment]
Check out v3 features here: http://fluent.stirno.com/the-journey-to-3-0/

Specifically the multi-browser testing bits.

**Comment by stirno** [comment]
I had a blog post around somewhere that I think I may have lost in the transition to/from various blog engines... but you can also use the NUnit TestCase attribute to 'pass in' the browser to the same method multiple times.

**Comment by dmcquiston** [comment]
How close is v3 to being released, roughly?

By the way I love what you've done with this library!

**Comment by stirno** [comment]
Thanks! Hoped to have it out a few days ago but its looking like this weekend now. I should mention that, while we have a significant test suite, due to resources and the feature being quite new -- our least tested bits are involved in multi-browser execution.

Several users have helped us find some bugs during this beta and we'd really appreciate you working with it too! :+1: We will be patching as quick as possible as we find issues, once we RTM v3. Happy to see FluentAutomation working for you!
