### ISSUE TITLE
Test runs with multiple screenshots ends up having only one screenshot

### ISSUE THREAD

**Issue by xerimaji** [stirno/FluentAutomation#114]
Looks like the name that the screenshot files are saved with is not unique enough. So if the test suite has more than one screenshot captured, only the last capture makes it.

**Comment by stirno** [comment]
Can you provide more details? Are you referring to screenshots taken with I.TakeScreenshot() or on Assert/Expect failures?

Also are you using v2 or v3? Thanks

**Comment by xerimaji** [comment]
Pardon the vague report. To clarify:
- This is with respect to screenshots taken on assert/expect failures
- I am using v3 beta, I had the same issue with v2 though.

I will commit a patch that sorted this issue out for me. If you think it's ok, I'll submit a pull request.

Thanks for such a helpful tool.

**Comment by stirno** [comment]
Sorry for not commenting on this, got crazy around here. Pulled your change in so we can push 3.0 with it. Reasonable fix, thanks!
