### ISSUE TITLE
I.UploadFile starts typing path to file before "Open" dialog pops up

### ISSUE THREAD

**Issue by xerimaji** [stirno/FluentAutomation#115]
Environment:
- FluentAutomation v3 beta
- SeleniumWebDriver
- Firefox 29, Chrome 34, Internet Explorer 11
- Windows Server 2008 R2
- VS 2013

When using `I.Upload("c:\temp\myfile.txt")` I notice that the "File name:" field in the "Open" dialog ends up with a file path like `temp\myfile.txt` -- notice the missing first few characters of the file path.

After some investigation, we noticed that it seems to start typing out the file name **before** the dialog comes up. The missing characters always show up in the input field that had focus before the file input is attempted.

If there is no reliable way to determine if the dialog is up before FluentAutomation starts typing the file name, we may have to resort to an artificial wait (guessing maybe 1000 ms) before the this.Type call.

**Comment by stirno** [comment]
Ya... not terribly surprised by this. So few people have used I.Upload that we don't get a ton of feedback on it. Paul and I will take another stab at this soon.

**Comment by xerimaji** [comment]
Excellent! I'll look forward to the official patch. In the mean time our team has a "pseudo-fix" that's basically "give the dialog enough time to show up", approach.

**Comment by stirno** [comment]
Used your 'pseudo-fix' for now, about to push 3.0 and wanted something in mainline since we haven't had time to take a look. Thanks!
