### ISSUE TITLE
I.Assert.Exists should fail instantly if there is no such element

### ISSUE THREAD

**Issue by vorou** [stirno/FluentAutomation#118]
`Expect` will fail instantly, but `Assert` will fail only after the timeout.

`I.Open(new Uri("http://google.com")).Expect.Exists("#cute-big-panda");`
`I.Open(new Uri("http://google.com")).Assert.Exists("#cute-big-panda");`

Is it by design? What should I use if I want test to fail (i.e., `Assert` behavior) instantly (i.e., as fast as `Expect` does)? 

It was mentioned [here](https://github.com/stirno/FluentAutomation/issues/84#issuecomment-37133489) already, but wasn't resolved.

**Comment by stirno** [comment]
You have a few options with 3.0.. You can either change the Wait behavior (globally or within the scope of this chain) or change the timeout value for Waits to be very low. I'd recommend the former.

```
With.WaitOnAllAsserts(false)
    .Then
    .Open("http://google.com")
    .Assert.Exists("#cute-big-panda");
```

This should trigger an immediate fail with no retry logic in a single block, but not affect the rest of your tests.

**Comment by vorou** [comment]
Oh, cool! Thanks for a quick response.

It works, but it looks like there is no global `WaitOnAllAsserts` in `FluentConfig`, only `WaitOnAllExpects` and `WaitOnAllActions`, so I had to use the old `Settings` object:

```
Config.Settings.WaitOnAllAsserts = false;
```

It's no big deal, of course. Thanks for your work!
