### ISSUE TITLE
Ability to capture screenshot on assert

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#12]

**Comment by stirno** [comment]
The path defaults to Environment.CurrentDirectory. To change it, in your test class override the Setup method and set the path. Example:

```
    public override void Setup()
    {
        this.ScreenshotOnAssertException = true;
        this.ScreenshotPath = @"C:\Users\stirno\Pictures\TestScreenshots";
    }
```

Notice the ScreenshotOnAssertException bool. When true, this will automatically take a screenshot when an assertion fails.

**Comment by stirno** [comment]
Added a method to deliberately take a screenshot.

```
I.TakeScreenshot(fileName);
```
