### ISSUE TITLE
PageObject documentation example is incorrect

### ISSUE THREAD

**Issue by MattLud** [stirno/FluentAutomation#120]
The current example for a page object does not compile by default. 

```
public class BingSearchPage : PageObject  
{
    public BingSearchPage(FluentTest test)
        : base(test)
    {
```

But PageObject is incorrect and should be using the generic class. 

```
//Still need to clarify what generic should be
PageObject<BingSearchPage> 
```

The first Assert does not work -

```
  At = () =>; I.Expect.Exists(SearchInput);
```

and should be 

```
  At = () => I.Expect.Exists(SearchInput);
```

**Comment by stirno** [comment]
That first one is likely an issue with the < and > not being escaped for the HTML. Last one is a typo.

We'll get it updated but PRs always welcome ;)

**Comment by MattLud** [comment]
Just saw the docs folder - cloning now :D
