### ISSUE TITLE
Chrome has conflicts when installed by administrator

### ISSUE THREAD

**Issue by bizcad** [stirno/FluentAutomation#122]
The Chrome driver gives the following message.  An administrator has installed Google Chrome on this system, and it is available for all users.  The system-level Google Chrome will replace your user-level installation now.
![chrome error](https://cloud.githubusercontent.com/assets/995059/3154491/b45dd78c-eaaa-11e3-9e12-45e2a63cfa1d.png)

**Comment by bizcad** [comment]
Close the ticket.  Problem resolved by deleting the file in users\myusername\AppData

**Comment by jrichards0305** [comment]
@bizcad What file specifically?

**Comment by jrichards0305** [comment]
@bizcad  Nevermind. I found it here: http://www.thecodingguys.net/blog/an-administrator-has-installed-google-chrome-on-this-system-and-it
