### ISSUE TITLE
The browser stays open when my application exits.

### ISSUE THREAD

**Issue by bizcad** [stirno/FluentAutomation#123]
I have a console app and a class library that references the FluentAutomation dlls.  I installed them with nugget command from the docs.  I then added the 5 dlls in packages.config to References in the Class library.  

When I run the console app, Firefox opens and the Assert Passes, but I do not have a way to close the Browser using the Selenium IWebDriver.Close() method.
## The console app

<pre>
using System;
using ProcessUITestFramework;

namespace ProcessUITestConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Press any key");
            ProcessUITestFramework.SampleTests tests = new SampleTests();

            tests.Test1();

            Console.ReadKey();

        }
    }
}
</pre>

## The class library ProcessUITestFramework

<pre>
using FluentAutomation;
namespace ProcessUITestFramework
{
    public class SampleTests : FluentTest
    {
        public SampleTests()
        {
            SeleniumWebDriver.Bootstrap(SeleniumWebDriver.Browser.Firefox);
        }

        public void Test1()
        {
            I.Open(@"http://Simon/Process/Home");
            I.Assert.Url("http://simon/Process/Home#Dashboard");
        }
    }
}
</pre>

**Comment by stirno** [comment]
Call Dispose on your Test class or wrap it in a using statement like so:

```
using System;
using ProcessUITestFramework;

namespace ProcessUITestConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Press any key");
            using (ProcessUITestFramework.SampleTests tests = new SampleTests()) {
                tests.Test1();
                Console.ReadKey();
            }
        }
    }
}
```

**Comment by bizcad** [comment]
The using works as well as calling Dispose on the test class.  Please close the issue.
