### ISSUE TITLE
Test Project won't load in Xamarin Studio

### ISSUE THREAD

**Issue by ashutoshraina** [stirno/FluentAutomation#142]
The test project won't open in Xamarin Studio because the project type is a VS Unit Test project.
I think since XUnit has been used a class library should suffice.

**Comment by csharpforevermore** [comment]
Adding the NuGet package XUnit VS Runner should allow Xamarin to load it. See http://xunit.github.io/docs/running-tests-in-vs.html. I've created a pull request to hopefully get this as part of the main solution.

**Comment by ashutoshraina** [comment]
I did try this and it did not work for me ..I guess the issue is that the project type is a VS Test project...a  simple class library should do the trick here...
