### ISSUE TITLE
How to run the test suite?

### ISSUE THREAD

**Issue by gaggle** [stirno/FluentAutomation#148]
Hi,

I load the solution in Visual Studio and, using Resharper, instruct it to run all tests.

The result is this:

<img width="1440" alt="tests" src="https://cloud.githubusercontent.com/assets/2316447/8908065/31461718-347a-11e5-91a4-c03fa5146cef.png">

No tests ever pass, I guess because they never connect to the local server? I'm pretty new to VS and C# though so I might be missing something obvious.. is there a guide to getting the test suite going?

**Comment by stirno** [comment]
You need to start the FluentAutomation.TestApplication site before you can run the tests.

**Comment by gaggle** [comment]
Oh. Well that makes sense...

Sorry if this is a daft question, but how does one do that? :)
