### ISSUE TITLE
Add negative assertions

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#15]

**Comment by stirno** [comment]
Working on a better solution to this.. but this is now doable via the Func<string, bool> support for Expects on Text/Value.

**Comment by stirno** [comment]
Updated the error output for expression based assertions to be more useful. This allows for a line like:

I.Expect.Text(x => !x.Contains("a")).From("selector");

This would validate that the chosen selector's text does not contain the letter A.

Closing this for now. Will revisit if a specific use case can't be met with this syntax.
