### ISSUE TITLE
Exception while running tests through Nunit 3.0.2

### ISSUE THREAD

**Issue by kiran-meda** [stirno/FluentAutomation#158]
Hi

I am getting following exception while running tests through nunit.
Exception System.Reflection.TargetInvocationException, Exception thrown executing tests in dll.

Thanks,
Kiran.

**Comment by stirno** [comment]
This is generally a wrapped exception where the InnerException property reveals more details of the actual problem. Not seeing any NUnit specific issues that I can reproduce.
