### ISSUE TITLE
Planing execution order of the tests

### ISSUE THREAD

**Issue by luisabarbosa** [stirno/FluentAutomation#159]
Does the FluentAutomation only works with unit test frameworks? Or is there any way of planing the execution order of the tests or to use the TestNG instead of Nunit/Xunit frameworks?
It would be a huge advantage if we would be able to planning the execution order of the test.

**Comment by stirno** [comment]
FluentAutomation leaves it up to the developer/tester to determine what framework executes the tests. The only requirement is that it be bootstrapped before the first `I.Open` is executed.
