### ISSUE TITLE
Internet window size should be user configurable

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#18]
IE window now maximizes and this should be user configurable

**Comment by jjohnson9730** [comment]
It is important to be able to see the url.  F11 isn't functioning to control size of window.

**Comment by stirno** [comment]
The intent of the tool isn't to visually validate its doing what it says. Its important the window run in fullscreen via WatiN to properly support drag/drop functionality.

**Comment by jjohnson9730** [comment]
Not all screens need drag/drop functionality.  In the real world, not all users are going to use an application in a full window, frequently they need to be able to open multiple windows within an IE.  I think  when "I.Use(BrowserType.InternetExplorer) should have an additional parm to indicate whether full screen or not.

**Comment by stirno** [comment]
Nothing about full-screen mode precludes use of multiple windows, or even tabs. In an automated testing scenario, its a non issue that it runs in full-screen to support lowest-common denominator in tests.
