### ISSUE TITLE
Assert failed on select options

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#20]
In firebug, this works:  $(".wizard select.It:eq(0)");

When using:  $(".wizard select.It:eq(0)"); this error occurs:
SelectElement value assertion failed. Expected element [.wizard select.It :eq(0)] to have a selected value of [Select...] but actual selected value is [string.Empty].

I am now able to get it to work with [.wizard select.It :eq(0) option:selected]

**Comment by stirno** [comment]
The example working selector is not the same as the one that error message was generated for.

**Comment by jasonjclifford** [comment]
I.Enter and I.Expect need ability to specify value or text of an option in a select list.

**Comment by stirno** [comment]
I.Select("text", SelectMode.Text).From("selector");

and

I.Expect.Text("text").In("selector");

in newest build.
