### ISSUE TITLE
Expect on element not comparing to correct actual value.

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#21]
FluentAutomation.API.AssertException: Value assertion failed. Expected element [div.error] to have a value of [User name or password is incorrect.] but actual value is [string.Empty].

Confirmed in jquery that when running:
$("div.error")
I get 1 result:
`<div class="error">User name or password is incorrect.</div>`

**Comment by stirno** [comment]
Comparing to value rather than text, which is inappropriate given the type of element. Will fix tonight.

**Comment by stirno** [comment]
The behavior of the Value function (formerly This()) still has a 'fallback' to Text for elements that don't have values.

I've added a new I.Expect.Text().In() method to guarantee only IElement.Text values are used in comparisons.

**Comment by stirno** [comment]
Checked in.
