### ISSUE TITLE
I.Expect returns true if object is not displayed

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#25]
With this code:

<div class="some-node">
    <span>test</span>
    <a style="text-decoration: none; font-size: 8px; display: none;" href="">add</a>
</div>

If I do an "I.Expect.This("add").In("some-node a:eq(0)"), it will not fail but should because "display: none"

**Comment by jasonjclifford** [comment]
In early discusses of this tool it was said that if an end user can't do it the tool shouldn't be able to do it.  In the case of hidden elements and using css selectors the css selector will be able to find things the user can't see.  If the tool tries click, enter, expect on something hidden it may make sense as a test may pass that the user actually couldn't do.  The question here is what cases could something be hidden and it is valid to interact with that element?

**Comment by stirno** [comment]
New code allows the MatchCondition behavior to be specified on Expects in scenarios where you need to guarantee that the item is visible. This keeps it flexible but allows the type of tests we're talking about here.

Example:

I.Expect.This("Beta").In("select:eq(0)", MatchConditions.Visible);

**Comment by stirno** [comment]
Expect syntax above checked in.
