### ISSUE TITLE
I.Expect.Index is needed

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#26]
If a row is entered on an UI, and the css selector is same for all items on the UI except for the :eq index number, I need to be able to get the index number of the customer identified by a title value.  

For example, the UI consists of a sorted grid with two columns.  In the first column it lists the customer in alpha order.  The next column is a delete buttons which correspond to the customer that the row it is on.

Customer        | Action    |Index  |
Dick's Bar and Grill    | Delete    |0  |
Don's Kwik Shop | Delete    |1  |
Joe's Bait Store    | Delete    |2  |
The Gas Station | Delete    |3  |

Now, if I add "Apple Pie Restaurant" to this, then all the indexes are going to change.  If I want to click the Delete button for Joe's Bait Store, I need to be able to get the index for Joe's Bait Store, so I can click the correct Delete button.

**Comment by jasonjclifford** [comment]
This seems to be an issue with the site not having proper attributes in place to use css selectors to get to the desired delete button.  The delete button should have a title attribute or the row should have some attribute to help identify the correct row.

**Comment by stirno** [comment]
I.Expect.Index isn't really an Expect/Assert at all. It seems like you're trying to get a value back from the page which is counter-intuitive to the intended test flow.

The thought is that you understand the data as it lives on the page because you control the test data. Retrieving data is not a priority in this scenario.
