### ISSUE TITLE
Return text of a css selector

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#27]
If a have a css selector such as: " .node a:eq({0})", I need to be able to pass in the index and have it return the text value of that css selector

**Comment by stirno** [comment]
This is counter to the intended flow of tests right now. In the future I'll look at supporting more options but this won't be a priority.

Tests should be written against a known data state and shouldn't rely on getting data from the page.

**Comment by marcusoftnet** [comment]
Yes! This is a great point. Could one ask for a wiki page (or somewhere in the docs) that describes the reasoning behind this and the benefits from going that route. 

I think this is common request and question and it would be great to have somewhere to point people. Hrfm of course it would help me a lot as I often fall into this "trap" myself ;)
