### ISSUE TITLE
Need ability to handle file upload dialog

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#28]

**Comment by stirno** [comment]
CI is running for this functionality now.. I.Upload(fileName, fieldSelector) is now implemented. The field selector is whatever needs to be clicked to load the upload dialog.

Selenium variant uses a fairly dirty thread sleep hack to make sure it gets the data in correctly. Hopefully no machine takes longer than 500ms to load the dialog.
