### ISSUE TITLE
Click that triggers page load doesn't wait

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#29]
Doing and I.Expect.Url right after I.Click that triggers a page load fails due to race condition. I.Expect.Url can trigger before the page has loaded and therefore compares against the previous page.

**Comment by stirno** [comment]
ClickNoWait change introduced this. Will revert that fix and a ClickMode to support NoWaits (such as where the user expects a dialog to launch which would otherwise lock the process).

**Comment by stirno** [comment]
confirmed this is fixed. Tested with:

```
    [TestMethod]
    public void Bug_29_UrlExpectNoWait()
    {
        I.Open("https://github.com/stirno/FluentAutomation/issues/29");
        I.Expect.Url("https://github.com/stirno/FluentAutomation/issues/29");
        I.Click("a[href='/stirno/FluentAutomation/network']");
        I.Expect.Url("https://github.com/stirno/FluentAutomation/network");
    }
```
