### ISSUE TITLE
I.Expect.Text returns invalid error message

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#30]
I.Expect.Text("Add").In("User.AddButton") - returns 'Value assertion failed.  Expected element [input[Value='Add']] to have a value of [Add] but actual value is [string.Empty]

Error message should be input[Text='Add']

**Comment by stirno** [comment]
The error message is accurate. That portion of the message is the selector provided to the Expect.

In this assertion, you've attempted to validate that the text of this input, a button given the selector, matches "Add". Buttons don't have an explicit Text setting so its set to string.Empty.

What you want is I.Expect.Value("Add").. having said that, if the selector includes a match for Value='Add'.. it doesn't seem like the best assertion to make.
