### ISSUE TITLE
I.Expect.Count(2).Of(something) fails

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#31]
If I expect count of 2 then I get an error 'Count assertion failed.  Expected there to be [2] elements matching [somevalue]].Actual count is [1].  

Count seems to be zero based and shouldn't be

**Comment by stirno** [comment]
Check the selector being used. Attempted to confirm issue with:

```
    [TestMethod]
    public void Bug_31_CountDoesntWork()
    {
        I.Open("http://knockoutjs.com/examples/controlTypes.html");
        I.Expect.Count(7).Of("input");
    }
```

This works as expected.
