### ISSUE TITLE
I.Expect.AnyValue("value1", "value2", ...).In()

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#32]
If a selector contains multiple elements the text content of each is mashed together for an I.Expect.Value.  Improve on this by allowing a list of values to compare to the content of a group of elements.

**Comment by stirno** [comment]
After some thought on this... whats being attempted is essentially a set of short-hand expects.

Doing this in a generic way will muddy the waters a bit where the Expect API already has many options. I think I can make this work but it will require a refactor of the current API which I'm not yet willing to commit to.

I will continue to look at this but I'm going to have to remove it from active milestones for now.
