### ISSUE TITLE
I.Expect.Value should be trimmed

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#33]
Value assertion failed. Expected element [.success-message ] to have a value of [Successfully added] but actual value is [Successfully added ].

The expected value is stored in a resource file which trims values but the actual value is not trimmed.  Actual value should be trimmed.

**Comment by stirno** [comment]
Can't do that as a rule... What if you wanted to verify a string that had spaces at the end?

**Comment by jasonjclifford** [comment]
Expect Value/Text should not automatically trim.  There are many cases where an extra space would be considered an error and automatically trimming this would create an invalid test.  An extra space like that is usually something the developer can remove which could be submitted as a bug.  In a special case where spaces are acceptable you can use the function argument I.Expect.Value(x => x.Trim() == "Successfully added");

**Comment by stirno** [comment]
I agree with Jason.

I.Expect.Value(Func<T>); works for this scenario.
