### ISSUE TITLE
Issue clicking item in list that closes when the list loses focus

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#34]
We have a textbox for search.  When you type in the textbox a list is displayed below it.  This list closes when you lose focus.  When trying to click on an item in the list I can see watin highlight the item that it clicked on but nothing seems to happen.  This works repeating the steps manually.  It seems that Fluent/Watin is causing some additional interaction from what a user would do that is causing this list to lose focus and close.

**Comment by stirno** [comment]
Presently ... we Focus a link before Clicking it, this is a general behavior before we forced onchange() events on the page. I will run the regression tests with the behavior removed and see where we end up.

**Comment by stirno** [comment]
Next build will have the Focus behavior disabled.
