### ISSUE TITLE
Ability to validate no duplicates are in a list

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#35]
We have a select list and a list of items can be added to it.  If an item is already there it should not be added to the list.  We need a way to validate that a list does not have duplicates or specify that a specific item is not duplicated.

**Comment by stirno** [comment]
I will look at this for a feature addition. for the moment, a Count expect would get the results you're looking for..

I.Expect.Count(1).Of("select option[value='Motorcycles']");
