### ISSUE TITLE
Ability to I.Click(x, y, selector) to click relative to an element on the page

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#36]
It is difficult to calculate a point from the corner of the screen which will not be consistent with screen resolution.  Need the ability to specify an element in the browser to be a point of reference from which the point is calculated

**Comment by stirno** [comment]
coming soon!

**Comment by stirno** [comment]
I.Click(selector, offset) is now implemented in my dev code.. will be pushed soon
