### ISSUE TITLE
I.Upload needs to work with a flash uploader

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#37]

**Comment by stirno** [comment]
I have this working with Selenium.. working on the WatiN variant still. Issues with its dialog handlers not triggering when a dialog is launched via a manual click event.

**Comment by stirno** [comment]
Just pushed a version that supports this via Selector+Offset for both Selenium and WatiN. Should be available from the CI build server soon, will be up on NuGet tomorrow as well.

I.Upload(fileName, containerSelector, offset);
