### ISSUE TITLE
Expect should handle attributes as well

### ISSUE THREAD

**Issue by mikeeast** [stirno/FluentAutomation#38]
It would be great to be able to do something like this:

I.Expect.Attribute("src").Value("tick.png").In("#my_img");

or is it already available?

**Comment by stirno** [comment]
Good call Mike. I'll get that in the build soon!

A workaround, that I don't love, short term would be to do:

I.Expect.Count(1).Of("#my_img[src='tick.png']");

**Comment by stirno** [comment]
I took it a step further to allow for some further element related expects.. Grab it from builds.stirno.com or GH and take a look. Its going through the CI build as I type.

Example:

```
[TestMethod]
public void Test_ElementExpression()
{
    I.Open("http://knockoutjs.com/");
    I.Expect.Element(x => x.GetAttributeValue("src") == "http://knockoutjs.com/img/feature-icons/declarative-bindings.png").In("li img:eq(0)");
}
```

The Nuget build will include this but I've been holding off on putting a new one out there until we finish the last tests on the new RemoteCommands API.

**Comment by mikeeast** [comment]
That looks brilliant!

When can we expect the Nuget package?

**Comment by mikeeast** [comment]
Oh, another thing. Please include the Assembly.xml files in the Nuget as well so that we can enjoy the API documentation in VS.

**Comment by stirno** [comment]
If not tonight, Saturday night I'll push a new build to Nuget.

Thanks Mike

**Comment by stirno** [comment]
1.0.0.85 is now up on Nuget for both WatiN and Selenium.

**Comment by mikeeast** [comment]
Nice!

Great job!

**Comment by vorou** [comment]
As far as I understood, the current way to do it is described [here](http://fluent.stirno.com/the-journey-to-3-0/) (New Asserts).
