### ISSUE TITLE
Hover doesn't work properly with Selenium

### ISSUE THREAD

**Issue by JudahGabriel** [stirno/FluentAutomation#42]
I.Hover('some-selector') isn't working properly on Selenium. The mouse moves, however, it doesn't appear to be scoping the hover in the context of the browser window.

**Comment by stirno** [comment]
Confirmed issue in Selenium provider, will fix this week. Thx Judah

**Comment by stirno** [comment]
Fixed correctly, finally.

**Comment by JudahGabriel** [comment]
About time, boy! ;-) Fix FluentAutomation bugs instead of TC Startup Weekend, eh?

**Comment by stirno** [comment]
for about 30 reasons, Startup Weekend didn't happen for me. Hopefully
Eric does something awesome.

On Sat, Feb 11, 2012 at 11:10 PM, JudahGabriel
reply@reply.github.com
wrote:
