### ISSUE TITLE
Add a property to access the current WebDriver

### ISSUE THREAD

**Issue by yetanotherchris** [stirno/FluentAutomation#44]
Great project - would it be possible to add a property to access your current WebDriver, i.e. FirefoxDriver. I'm not sure how it would with I, something like

```
I.GetDriver().FindElement(By.Name("q"))
```

I need this as sometimes Sizzle break with jQuery, or doesn't give us the ability to do a text search of the innerHtml.

**Comment by stirno** [comment]
I hesitate to provide direct access to the underlying driver, mostly to avoid users being unable to use a different driver later, but also to maintain the ability to use the I.Record/I.Execute feature. Not ruling it out if a scenario pops up that can't be solved without doing it though.

Can you highlight a few specific examples where you're having an issue? I have been looking at providing expression based selectors for advanced scenarios (similar to I.Expect.Element(Func)).

**Comment by yetanotherchris** [comment]
There's functionality like providing a profile for the FIrefox, or avoiding using contains() everywhere for text, or the page source. I can see the argument for encapsulating the driver and hiding it from the user, it's just sometimes I want to access the Selenium core without completely ditching the fluent API and having to go back to the Selenium webdriver setup.

I've got around a few of the problems by having a set of extension methods:

public static void ClickButtonWithValue(this CommandManager manager, string buttonValue)
{
    manager.Click("input[value='" + buttonValue + "']");
}

public static void ClickLinkWithText(this CommandManager manager, string linkText)
{
    manager.Click("a:contains('" + linkText + "')");
}

public static void ClickLink(this CommandManager manager, string idEndsWith)
{
    manager.Click("a:id[$=('" + idEndsWith + "')");
}

public static void FillTextBox(this CommandManager manager, string idEndsWith, string value)
{
    manager.Enter(value).In("input[id$='" + idEndsWith + "']");
}

**Comment by yetanotherchris** [comment]
I've just looked through the code and realised why it would be messy, as FluentAutomation.API.Providers.AutomationProvider doesn't define GetDriver as it's Selenium specific.

Would you consider changing the FluentAutomation.SeleniumWebDriver.getDriver to protected? Then any derived classes can access it without breaking the core AutomationProvider, from what I can tell.

**Comment by stirno** [comment]
The trick will be to compile an AutomationProvider, reference it so it can be loaded by the new setup and then you're free to do what you want.

The other part that will be dirty is the ActionBucket for recording methods. We'd have to do something like:

```
I.TakeAction(provider => ....);
```

where provider can be cast to a type that exposes GetDriver().. Lets keep throwing ideas around on this and see if we can find something that works

**Comment by yetanotherchris** [comment]
There's a few options can see:

1) Write my own AutomationProvider - but it would end up being an exact clone of the existing Selenium one, with the access modifier changed.

2) You change the method to protected then I could subclass the Selenium AutomationProvider, create a public method to call the protected method, and I create my own FluentTest class/use the base FluentTest which looks like it uses discovery from the config file to find an AutomationProvider.

3) Change to public in the selenium AutomationProvider

4) I stop pestering you + I branch the project :) But I'd prefer not to as I'd hoped to just keep a nuget reference

**Comment by stirno** [comment]
Ya.. we can make this happen, just gotta provide a hook so people who choose to do this can maintain record/execute functionality and possibly RemoteCommand API functionality.

Less about how to get the driver out so you can work with it, more about how you can make sure your action is tracked/repeatable by the API.

**Comment by yetanotherchris** [comment]
A minor update to what I said: the getDriver method doesn't needs to be changed, but

```
    private IWebDriver _driver = null;
```

to

```
    protected IWebDriver _driver = null;
```

It looks like the webdriver doesn't give you access to the profiles after construction anyway, so adding this is probably not what I need. It'd be nice if the fluent API could have the Quit, Manager().DeleteCookies methods that the IWebDriver gives, and also a method to return an IWebElement (unless that already exists, I'm not sure).

Those are really all I need from the Selenium api.

On Sat, Nov 12, 2011 at 2:16 AM, Brandon Stirnaman <
reply@reply.github.com
