### ISSUE TITLE
OnChange causes an UnexpectedJavascriptError in IE9

### ISSUE THREAD

**Issue by yetanotherchris** [stirno/FluentAutomation#45]
In the SeleniumWebDriver.Element.OnChange method (line 121) has problems with IE, including IE9:

```
    public virtual void OnChange()
    {
        ((IJavaScriptExecutor)_driver).ExecuteScript(string.Format("if (typeof jQuery != 'undefined') {{ jQuery(\"{0}\").click(); }}", _fieldSelector.Replace("\"", "")));
    }
```

The answer appears to be to use click(), from this discussion: http://stackoverflow.com/questions/208471/getting-jquery-to-recognise-change-in-ie

Or if you're using jQuery 1.5 the problem is resolved but unfortunately we're using jQuery 1.3.

Once I setup Github I'll try to push a patch

**Comment by stirno** [comment]
I'm hesitant to use click to hack that. We should probably look at firing the explicit OnPropertyChange event for IE and see if that gets the desired behavior.

Can you take a look at that? I'll get setup to test this tonight also.

**Comment by stirno** [comment]
Going to try this out in a bit with jQuery 1.3, IE9.. Thought more about it, I'm worried about what other types of odd things might happen if we start triggering a click event as often as we do the OnChange.

**Comment by yetanotherchris** [comment]
I still had the problem with jQuery 1.5 so that information may have been incorrect, or 1.6 fixes it.
