### ISSUE TITLE
"No automation provider available"

### ISSUE THREAD

**Issue by Hainesy** [stirno/FluentAutomation#50]
Trying to get this working with Xunit + Selenium WebDriver + Resharper Test Runner

All I get back is System.InvalidOperationException: No automation provider available.

I have the relevant Nuget packages installed:

<package id="FluentAutomation.SeleniumWebDriver" version="1.0.0.97" />
<package id="Selenium.WebDriver" version="2.22.1" />

Is something not copying correctly when the test runner runs?

**Comment by marcusoftnet** [comment]
Could this help; http://www.marcusoft.net/2012/05/systeminvalidoperationexception-no.html

**Comment by Hainesy** [comment]
Hi Marcus

I had already read your blog post, which pointed me in the right direction, but as I'm not using MsTest it doesn't really show me what the solution is for xUnit....

**Comment by marcusoftnet** [comment]
Ah - fingers crossed for a simple solution then

**Comment by stirno** [comment]
I use xUnit for the CI tests without issue. Happens in v1 when the FluentAutomation.SeleniumWebDriver.dll assembly can't be found in the bin folder.

I'll setup the R# test runner this weekend and try to replicate the problem. Using the VS11/2012 xUnit runner has worked great for me.

Thanks for the issue report

**Comment by Hainesy** [comment]
Hi

Did you have any joy over the weekend?

Thanks

Chris

**Comment by stirno** [comment]
Total lack of updates on this, I apologize. Can you try and repro this with the v2 code/nuget package? I can't currently, but I'll be testing it again on a totally unbiased setup (not screwed with by my own fluent dev tools) later this week.

Thanks!

**Comment by Hainesy** [comment]
Hi

Sorry too late, I've switched to nUnit... :-)

**Comment by stirno** [comment]
Unable to repro with current code. Closing for now
