### ISSUE TITLE
Quickly is missing from vNext

### ISSUE THREAD

**Issue by marcusoftnet** [stirno/FluentAutomation#51]
Hello, 

we've tried out the version that is under development right now (brought down the codez, compiled and used it), and we're missing the Quickly-way of entering text. That is - no events firing. 

Is this by design or has it slipped away

**Comment by stirno** [comment]
It was, essentially, a design choice but I want to bring it back with a more direct API.. i.e. Quickly didn't really properly describe what it was doing.

**Comment by stirno** [comment]
In source and on NuGet pre-release.. I.Enter("").WithoutEvents().In() is the new wording.. Funny enough, the Selenium implementation of v1 doesn't actually do this properly. This may be buggy, I don't have a good set of tests for this particular function.

**Comment by pauljz** [comment]
Is it worth including a deprecated .Quickly() syntax implementation just for backwards compatibility? Seems to come up a lot.

Or alternatively to have it throw an Exception right away saying to use WithoutEvents.

**Comment by stirno** [comment]
Ya, we can throw a helper in to do that. Can't actually Deprecate it because of several projects using Warnings as Errors for compilation in VS.

We'll list it as deprecated in the docs and add a comment to that effect on the method.

**Comment by stirno** [comment]
Its back in source now and will be in the final v2 release. Comment states it is deprecated and will be removed at some point in the future.
