### ISSUE TITLE
update webdriver from 2.19 to 2.24

### ISSUE THREAD

**Issue by vgirard** [stirno/FluentAutomation#52]
Since I have some problems with WebDriver when running tests in batch is it possible to update to the latest version? Thanks!

**Comment by couellet** [comment]
I got the same problem! +1

**Comment by stirno** [comment]
I'm working on this tonight for the v2 code on GH. It'll get pushed to nuget when v2 gets past the CI

**Comment by stirno** [comment]
Just updated to v2.25 for Fluent v2. Also published as a pre-release on NuGet.
