### ISSUE TITLE
No access to AutomationProvider.Authenticate() through FluentTest

### ISSUE THREAD

**Issue by dalager** [stirno/FluentAutomation#53]
Apparently there's some authentication logic within the AutomationProvider, but it's not clear how to expose that to a test.

Is this a case where I just create my own AutomationProvider/CommandManager and or what are your intentions with that basic auth logic?

(might not be a bug)

**Comment by stirno** [comment]
The AutomationProviders in v1 did have some code to attempt to handle HTTP authentication but I never got it working 100% so it was removed from the exposed syntax.

It was not replicated in v2, which we are currently preparing for release. Need to re-prioritize this versus the other edge features for v2.

**Comment by dalager** [comment]
Ah. That explains it.
Well, consider this an upvote for the functionality :)

c

**Comment by stirno** [comment]
Created new Issue #58 to cover Basic HTTP Auth support. Targeted for the next release!
