### ISSUE TITLE
New IE webdriver can block browser window

### ISSUE THREAD

**Issue by TroyWalshProf** [stirno/FluentAutomation#55]
The new IE webdriver launches an command line window when it starts.
Selenium has a habit of pushing the IE browser to the background.
The result is your automation fails because the webdriver command line window is in the way.

**Comment by stirno** [comment]
Newest push added Settings.MinimizeAllWindowsOnTestStart (defaults to true) which should alleviate this. Most properly implemented applications will be minimized. Notable exceptions are GTalk and a few with custom window drawing bits.

**Comment by TroyWalshProf** [comment]
The IE webdriver command line window, which is the main problem, does not get minimized.
