### ISSUE TITLE
Chrome browser is not maximized with Selenium

### ISSUE THREAD

**Issue by TroyWalshProf** [stirno/FluentAutomation#56]
The chrome driver for Selenium does not maximize the browser.

It would be nice if chrome were launched with options kind of like this:
   OpenQA.Selenium.Chrome.ChromeOptions options = new OpenQA.Selenium.Chrome.ChromeOptions();
   options.AddArgument("--start-maximized");
   container.Register<OpenQA.Selenium.Chrome.ChromeDriver>().UsingConstructor(() => new OpenQA.Selenium.Chrome.ChromeDriver(options));

**Comment by stirno** [comment]
Covered by new Issue #57
