### ISSUE TITLE
Allow user to manage window state/size

### ISSUE THREAD

**Issue by stirno** [stirno/FluentAutomation#57]
For easier testing of reactive UIs, allow the user to set the opening size of browser windows and their maximized/minimized states.

**Comment by TroyWalshProf** [comment]
I have been able to get around this by passing parameters into the chromedriver.exe driver, but I don't know how to pass in parameters given the the way it gets registered:
container.Register<IWebDriver, OpenQA.Selenium.Chrome.ChromeDriver>().AsMultiInstance();

**Comment by iblazhev** [comment]
Hi @stirno, I found this as very nice framework, I hope you will fix this issue #57   soon :)

**Comment by stirno** [comment]
This got left hanging around but, Settings includes window size options now. Closing
