### ISSUE TITLE
Need ability to click browser back button

### ISSUE THREAD

**Issue by jasonjclifford** [stirno/FluentAutomation#6]

**Comment by stirno** [comment]
Working on this, but WatiN is acting somewhat oddly. Clicking a button for example, isn't causing the browser to add a new item to history. So the Back button call doesn't do anything.

**Comment by stirno** [comment]
So this is checked in currently. Available via I.Navigate(NavigationDirection.Back) in your test. Its still having issues but I figured it could get thrown in for now. Seems to work via Selenium more consistently than WatiN.

**Comment by stirno** [comment]
Resolved but issue lies within either local IE or WatiN. Will investigate later. Closing issue for now.
