### ISSUE TITLE
Error screenshot

### ISSUE THREAD

**Issue by nishant7k** [stirno/FluentAutomation#60]
Hi

Can we have flexibility to take the screenshot if any of the step fails? Like I.Click("abc"). Where "abc" not found on the screen and it will throw the exception. And it will go to error page. But can we take the screenshot in that case. I guess we should not use and if or try catch block as it will create problem for the recorder ( it won't be fluent in that case). Suggest please.

**Comment by stirno** [comment]
This was a feature of the v1 codebase, I'm in progress implementing it now.

**Comment by stirno** [comment]
Sorry for the delayed update.. Automatic error screenshots are implemented now. I'm doing some quick testing but it will be in the next v2 push on NuGet and is in Git now.

**Comment by stirno** [comment]
To support this feature, in v2, there are now two settings that can be changed to use this:

Settings.ScreenshotOnFailedExpect -- Set to true to automatically take a screenshot when an expect fails (Anything that throws FluentExpectFailedException).
Settings.ScreenshotOnFailedAction -- Set to true to automatically take a screenshot when an action fails (Everything else Fluent does).

It will save the screenshots to the path specified in Settings.ScreenshotPath.
