### ISSUE TITLE
Question: How can I obtain Watin element or a reference to current browser

### ISSUE THREAD

**Issue by LSTANCZYK** [stirno/FluentAutomation#61]
I need to be able to perform some things that are not implemented with fluent automation and woudl like to be able to get a hold of the brtowser or Watin element. I am acctually trying to run a linq query such as this: 

```
var indicators = from i in this.CurrentBrowser.Links
                             where i.Url.Contains("LeadsMine.aspx?flag")
                             select i;
```

Thank you in advance!

**Comment by pauljz** [comment]
@Stirno can correct me if I'm wrong, but I believe this is unsupported in version 1 of the API. It's one of the big features that prompted the rewrite for version 2.  If you upgrade to 2.0-alpha (available as an [alpha Nuget package](https://nuget.org/packages/FluentAutomation.WatiN/2.0-alpha2)) you can do this using something like `I.FindMultiple('a[href*=LeadsMine.aspx?flag]');`

This returns [FluentAutomation.Element](https://github.com/stirno/FluentAutomation/blob/master/FluentAutomation.WatiN/Element.cs), which you can use to get data.

Nice thing about this approach is that it's still abstracted away from WatiN should you ever need to switch providers.

**Comment by stirno** [comment]
@pauljz is correct. There is no direct access to the underlying providers in either v1 or v2 but you can use the advanced I.Find/I.FindMultiple accessors to handle advanced bits where you need to aggregate multiple entities that match a selector.

**Comment by LSTANCZYK** [comment]
Ok that makes sense. Another reason why I needed to be able to get a hold of Watin was to be able to run Javascript like this:

```
string scriptStr = "var i = {0}.FindItemByText('{1}');{0}.SetValue(i.value);";
            string script = string.Format(scriptStr,comboName,itemText);
            Trace.WriteLine(script);
            ie.RunScript(script);
            ie.WaitForComplete();
```

is this possible with Fluent Automation

**Comment by pauljz** [comment]
Injecting scripts into the DOM or directly altering the DOM isn't currently supported. You would need to expose the functionality via a JavaScript event of some kind (e.g. sticking it in an onclick).

I could see a case for an `I.Inject()` command being added, to drop in JavaScript, but I'm not sure it fits philosophically. You're then introducing code/functionality that does not exist into the environment being tested, rather than just working with existing code.

I'll let @stirno weigh in again on the matter, but I wanted to make sure you at least got an answer quickly.

**Comment by LSTANCZYK** [comment]
@pauljz Thank you for a swift response. The reason why i need to be able to use Javascript is that in order to functionaly test my site that uses DevExpress controlls I need to be able to interact with them somehow. Since they are not native drop down lists for instance  in order to select an element I have to go through their client side API. I write my own extension methods so i can do `I.SelectFromDevExpressCombo(combo name,value)` but still I need the javascript for the implementation of that extension method. (hope this makes sense)

**Comment by LSTANCZYK** [comment]
Actually I got this to work with following code: 
To run the script: 

```
 public static void RunScript(this FluentAutomation.Interfaces.INativeActionSyntaxProvider I, string scriptCode)
        {
            FluentAutomation.Element bodyTag = I.Find("body").Invoke() as FluentAutomation.Element;
            bodyTag.AutomationElement.DomContainer.RunScript(scriptCode);
        }
```

and then I can have my extension method to select from my DevExpress combo:

```
public static void SelectFromDevExpressCombo(this FluentAutomation.Interfaces.INativeActionSyntaxProvider I, string comboName, string itemText)
        {
            string scriptStr = "var i = {0}.FindItemByText('{1}');{0}.SetValue(i.value);";
            string script = string.Format(scriptStr,comboName,itemText);
            I.RunScript(script);
        }
```

**Comment by stirno** [comment]
This is definitely a workable solution. I'll add a user-request item to my list for executing JS on the page without having to break out of the provider abstraction.

Thanks!
