### ISSUE TITLE
Button is not identified, if its not be seen on the screen

### ISSUE THREAD

**Issue by nishant7k** [stirno/FluentAutomation#67]
I am using it for my single page app. Once the button goes out of screen view, fluent automation is not able to identify it and throws the exception. Again i scroll it down and bring the button in view then it works fine.How can we handle it. Can we have I.ScrollDown() kind of method? Please suggest .

**Comment by nishant7k** [comment]
Infact this is happening with all clickable element. Surprisingly, it works bit ok (still fragile) in firefox, but not at all in Chrome.

**Comment by pauljz** [comment]
Hi @Nishanttiwari, what version are you using, and which driver (Selenium/WatiN)? I feel like we fixed this issue recently, but I might be mistaken.

**Comment by nishant7k** [comment]
Hi @pauljz , I am using the latest version of fluent automation(2.0.0.2), driver is selenium.It is not working with latest version as well.

**Comment by nishant7k** [comment]
Hi @pauljz , Is there any workaround for it?

**Comment by stirno** [comment]
@Nishanttiwari - Sorry for the lack of answers thus far. The Thanksgiving holiday has kinda screwed up our schedules a bit. After work tonight I'll attempt to repro and provide a workaround/update/continue the conversation on this issue.

Thanks for your patience!

**Comment by nishant7k** [comment]
Hi @stirno Thanks for your quick response on this. Actually, I think the problem is with the Click method. Its not able to identify the element on the screen if its not visible within current window. I am trying something like  I.Click("span.asset-tracked"); The span is on the screen, but I need to scroll down to see it. Once its in view then the click event works. Else not. Please let me know if you need further details on it.

**Comment by stirno** [comment]
Just to throw an update out there for you.. I can repro this in a few scenarios. No workaround yet, working on it.

**Comment by nishant7k** [comment]
Hi @stirno , any luck with this?

**Comment by stirno** [comment]
Not reproducible for me on the 3.0 branch.. wish I didn't leave this out there so long, sorry @Nishanttiwari
