### ISSUE TITLE
TypeError: 'undefined' is not a function

### ISSUE THREAD

**Issue by 0liver** [stirno/FluentAutomation#68]
Just installed the freshest NuGet bits today (version 2.0.0.2) and wrote my first test class. Unfortunately, I can't get beyond the following error:

```
Connecting to ws://127.0.0.1:8050 ...
Running: {"action":"Navigate","url":"http://www.heise.de/suche/"}
Running: {"action":"Find","selector":"input#search_q"}
Running: {"action":"EnterText","selector":"input#search_q","text":"SSD"}
TypeError: 'undefined' is not a function

  PhantomDriver.coffee:43
TypeError: 'undefined' is not a function
```

My test class is:

```
[TestFixture]
public class FormTest : FluentTest {
  public FormTest() {
    PhantomJS.Bootstrap();
  }

  [Test]
  public void First() {
    I.Open("http://www.heise.de/suche/");
    I.Enter("SSD").In("input#search_q");
    I.Click("form#searchbox input.search_submit");
    I.Expect.Text("mehr als 1000 Treffer");
  }
}
```

I have neither used FluentAutomation nor PhantomJS before today, but would have expected this simple test to just work.

**Comment by stirno** [comment]
I'd agree, this should have just worked. We do have lots of work to do with the PhantomJS driver in particular. I threw it up on NuGet to get some feedback on it from interested parties and see if anyone was interested in using it.

We are focusing some effort on getting it more feature comparable to our Selenium and WatiN drivers, and at one point it was nearly there. There are however a few current issues with callback completion that cause issues like you encountered.

Thanks for the report and sorry for the delay. Vacation was way more relaxing than I'd thought it would be.

**Comment by 0liver** [comment]
Thanks for following up on this. For now, we're sticking with our own setup
but I'll be tracking the project's progress.

" Vacation was way more relaxing than I'd thought it would be. " - Glad to

## hear that!

2012/12/30 Brandon Stirnaman notifications@github.com

> Vacation was way more relaxing than I'd thought it would be.

**Comment by stirno** [comment]
Going to be pulling the PhantomJS driver and adding support for Phantom into our SeleniumWebDriver bits soon.
