### ISSUE TITLE
IE9 An error ocurred while locating an element via jQuery/Sizzle. InnerException may have more details.

### ISSUE THREAD

**Issue by michaelhidalgo** [stirno/FluentAutomation#69]
Hi Folks,
I've created a test automation script using your API that works very well in Firefox, Chrome, but it does not seems to be working in IE (not surprising).
I do have a wait sentence to determine when a div as loaded, this is the code:

I.WaitUntil(() => I.Expect.Exists("#topRightMenu"));

But at the time to running it in IE, I got a timeout exception and looking at the InnerException, I found this error An error ocurred while locating an element via jQuery/Sizzle. InnerException may have more details.

I'm not sure if this is an issue, but it works fine for other browsers.

Any Ideas?

![error](https://f.cloud.github.com/assets/1732035/46617/a9235a66-587c-11e2-840c-c095aff93274.png)

**Comment by stirno** [comment]
Silly question perhaps but does the block exist in IE?

**Comment by michaelhidalgo** [comment]
what do you mean by block? when I run the test I can see that IE browser is displayed and I can actually see the div (it has been rendered), but I got a timeout.

**Comment by stirno** [comment]
Sorry, the element with an ID of topRightMenu. I'll try and repro this tonight. What version of IE do you use?

Thanks

**Comment by michaelhidalgo** [comment]
Thanks, I'm currently using IE 9. Thanks for your help.

**Comment by stirno** [comment]
Wow.. this got dropped somehow. Sorry @michaelhidalgo - Going through the issues today and cleaning up. Do you still have this issue? I can't repro in the versions of IE easily available to me at the moment.

**Comment by pauljz** [comment]
I set up a clean Win7/IE9 VM and tried to reproduce against @michaelhidalgo's site. So far everything looks okay using FluentAutomation 3.0.0 and IEDriverServer v2.41.0.

The code I'm using: https://gist.github.com/pauljz/9862146
