### ISSUE TITLE
Support for more Selenium Drivers

### ISSUE THREAD

**Issue by mahic** [stirno/FluentAutomation#71]
SeleniumWebDriver.Bootstrap() currently supports only Firefox, IE and Chrome. 
There is no support for the new PhanomJs driver added in Selenium 2.28.
There is also support for Opera, Safari or RemoteDriver so tests can be run against a Selenium Grid.

**Comment by stirno** [comment]
Adding support for the other Drivers is definitely something we're going to work on, but its been slow lately. Its the area I'd most like to see some pull requests to assist with.

**Comment by stirno** [comment]
This took a long time for me to come back and resolve.. but 2.1 added support for RemoteWebDriver via passing a URI, as well as PhantomJs directly in Selenium. Updated in 2.2 to be even better :)
