### ISSUE TITLE
Certain operations/drivers require several attempts

### ISSUE THREAD

**Issue by object** [stirno/FluentAutomation#74]
When using FluentAutomation with SeleniumWebDriver/Chrome, there are often exceptions "No response from server for url..." are thrown. To make tests stable I had to wrap some operations with retry code:

```
    public static void ClickOn(this INativeActionSyntaxProvider I, Func<IElement> element)
    {
        Try(I, () => I.Click(element));
    }

    public static void ClickOn(this INativeActionSyntaxProvider I, string selector)
    {
        Try(I, () => I.Click(selector));
    }

    private static void Try(this INativeActionSyntaxProvider I, Action action)
    {
        const int maxAttempts = 5;
        for (var currentAttempt = 0; currentAttempt < maxAttempts; currentAttempt++)
        {
            try
            {
                action();
                return;
            }
            catch (Exception exception)
            {
                if (currentAttempt < maxAttempts && ShouldRetry(exception))
                {
                    ++currentAttempt;
                }
                else
                {
                    throw;
                }
            }
        }
    }

    private static bool ShouldRetry(Exception exception)
    {
        var exceptions = new Exception[] {exception, exception.InnerException};
        foreach (var e in exceptions)
        {
            if (e != null && e.GetType().FullName == "OpenQA.Selenium.WebDriverException" &&
                e.Message.StartsWith("No response from server for url"))
            {
                return true;
            }
        }
        return false;
    }
```

This has nothing to do with FluentAutomation, it's just WebDriver, but since this is a general problem, perhaps Settings can be extended with a value for maximum attempts?

**Comment by stirno** [comment]
Hmm.. I haven't run into this directly but I can definitely support some built-in retry logic for WebDriver failures. Good call.

**Comment by object** [comment]
I think this is easy reproduceable on FluenAutomation tests. I ran them using Visual Studio 2012 on Windows 7 with Chrome driver, and this exception frequently occurs. If you need more info, I can elaborate.

**Comment by stirno** [comment]
Ya I have no doubt you are seeing it consistently. I have had reports from another user with a similar issue related to a mismatch between the ChromeDriver.exe we package and the latest versions of Chrome (this user was on the Dev channel). I'm working on some bits to help more easily pull latest drivers for Chrome and IE to help there.

Having said that, there are enough possible failures that can occur that your suggestion of built-in Retry logic for WebDriver commands certainly has merit. Just need to evaluate which commands make sense to do that for. Timeouts are certainly a top contender.

**Comment by stirno** [comment]
Can you repro this with the latest (2.2.0.1)?

**Comment by object** [comment]
I belive it works fine now, starting at least with 2.1.0.1. I removed recently my retry logic and it works great.

**Comment by object** [comment]
Actually I was wrong when I said I had earlier removed retry logic. It was still in my code until now. But I am running my tests with 2.2.0.1 without any retry logic, and they work fine.
