### ISSUE TITLE
Is there support for checking the state of buttons?

### ISSUE THREAD

**Issue by object** [stirno/FluentAutomation#75]
Hi,

I've been successfully using FluentAutomation in a couple of projects, but unless I overlook something, I can't find an easy way to inspect states of controls, e.g.:
- I expect the button ABC to be disabled;
- I expect the checkbox XYZ to be checked;

Etc.

In case such inspection is the part of test, what is the best way to approach it using FluentAutomation?

**Comment by stirno** [comment]
The best way to do this is with the Sizzle attribute selectors [disabled, checked] with Exists or Count:

```
I.Expect.Exists("button[disabled]");
I.Expect.Count(1).Of("button[disabled]");

I.Expect.Exists("input[checked]");
I.Expect.Count(1).Of("input[checked]");
```

**Comment by object** [comment]
Thanks! That will do.
