### ISSUE TITLE
Documentation: No documentation about Enter() function

### ISSUE THREAD

**Issue by TimGebhardt** [stirno/FluentAutomation#77]
On this page: http://fluent.stirno.com/docs/ there's no documentation about the Enter().In() syntax, which I believe is the preferred syntax for entering text.

**Comment by stirno** [comment]
wow. You are correct. +10pts for you. I'll get it up there with 2.3 Docs this weekend.

Thanks a ton for the report!

**Comment by stirno** [comment]
2.3 Docs (and new site) up now. Took an extra week to get it finished (or .. started. oops.)

Check out the docs and let me know if you see anything else missing!

**Comment by pf-kenneth-hamlin** [comment]
Hey where is your docs that used to live here: http://fluent.stirno.com/docs/
