### ISSUE TITLE
Disabling driver(chrome driver) logs.

### ISSUE THREAD

**Issue by Thejas007** [stirno/FluentAutomation#79]
Hi @stirno ,

I'm using nspec for writing tests with chrome driver, but chrome diver logs were filled with package manager console. Any option is there to provide the logs to be disable.

**Comment by stirno** [comment]
Chromedriver does get a bit spammy. I'll look into this.

**Comment by stirno** [comment]
v3.0 basically does everything it can to silence chromedriver output except for actual errors.

**Comment by stirno** [comment]
Confirmed working as best as we can right now in the 3.0 branch (fixmultibrowsertesting -- stupid name I know..). Should be up on NuGet in a few days.
