### ISSUE TITLE
Send Keys

### ISSUE THREAD

**Issue by jjohnson9730** [stirno/FluentAutomation#8]
Need the ability to sendkeys - tried to use:

System.Windows.Forms.SendKeys.SendWait("TAB");

but no luck

**Comment by stirno** [comment]
Windows Form key events won't do the trick. There will be an ability to send special keystrokes soon.

**Comment by jjohnson9730** [comment]
Cool!  Thanx!

**Comment by stirno** [comment]
I.Press() is now implemented. It takes a string that feeds into SendKeys.SendWait under the covers. Will replace with an enumeration based, compile-time safe method later.
