### ISSUE TITLE
Update for phantomjs needed

### ISSUE THREAD

**Issue by halex2005** [stirno/FluentAutomation#80]
I just found that in nuget package for FluentAutomation.SeleniumWebDriver you use PhantomJS v1.9.6.
That version of PhantomJS has an issue with GhostDriver that has been fixed in v1.9.7 (rollback for GhostDriver).

Links for issue with PhantomJS is here:
https://github.com/ariya/phantomjs/issues/11915
https://groups.google.com/forum/#!msg/phantomjs/ouFiiB1UoLw/qnB8RZgV3yUJ

**Comment by stirno** [comment]
I'll package the update with 2.3.0.1

**Comment by stirno** [comment]
Pushed to dev and nuget with 1.9.7 -- also updated ChromeDriver to 2.9 while I was in there.
