### ISSUE TITLE
WaitUntil(Action) error

### ISSUE THREAD

**Issue by b26** [stirno/FluentAutomation#83]
I'm running a script through 'Fluent Automation Console'. Here is my output: 

> using FluentAutomation;
> var test = new FluentTest();
> SeleniumWebDriver.Bootstrap(SeleniumWebDriver.Browser.Chrome);
> Settings.MinimizeAllWindowsOnTestStart = false;
> false
> Settings.DefaultWaitUntilTimeout = TimeSpan.FromSeconds(1);
> "00:00:01"
> 
> var I = test.I;
> I.Open("http://www.google.com")
> Starting ChromeDriver (v2.3) on port 53438
> [9052:20412:0306/154732:ERROR:chrome_views_delegate.cc(185)] NOT IMPLEMENTED
> [9052:20412:0306/154732:ERROR:desktop_root_window_host_win.cc(760)] NOT IMPLEMENTED
> [9052:20412:0306/154732:ERROR:desktop_root_window_host_win.cc(760)] NOT IMPLEMENTED
> An unexpected exception was thrown inside WaitUntil(Action). See InnerException for details.

**Comment by stirno** [comment]
Just to add a comment on this for anyone who stumbles on it - the output shown here is from chromedriver.exe and is generally normal. The last line indicates an exception occurred when opening the page but there isn't enough detail to debug further.

I assume @b26 resolved the issue as it was closed. Thanks!
