### ISSUE TITLE
Opposite of Expect.Exists

### ISSUE THREAD

**Issue by AnthonySteele** [stirno/FluentAutomation#84]
Sometimes I want to do the simple negation of I.Assert.Exists("#searchBar");
e.g. "when the user is logged in, I should see a "you are logged in as..." span **and**
"when the user is not logged in, I should not see a "you are logged in as..." span

Syntax something like in NUnit: like`I.Assert.Not.Exists("#searchBar");` or  `I.Assert.DoesNotExist("#searchBar");`

Currently I  do this:
    `var searchbar = page.I.FindMultiple("#searchBar")();
    Assert.False(searchbar.Any());`

**Comment by stirno** [comment]
A better way to do this in the current API would be

```
I.Expect.Count(0).Of("#searchBar");
```

We can look at adding some syntactical sugar for this but most users use it this way.

**Comment by AnthonySteele** [comment]
That is simpler, thanks. I will try it.

Though what I like about NUnit  (e.g. `Is.Not.Null`) are that the syntax for negating a check is a very minor change; it is closely related to the original check.

**Comment by dauger** [comment]
One thing that I've noticed is that when Expecting or Asserting for the nonexistence of something, the framework will wait for the timeout value. Waiting could be the desired behavior in some circumstances, but so could not waiting.

Here is my current work around for not waiting:

``` csharp
// assume Settings.ExpectIsAssert = false;
Settings.WaitOnAllExpects = false;

I.Expect.Count(0).Of("#someThing");

Settings.WaitOnAllExpects = true; // go back to defaults
```

Is there a better way to handle the nowait scenario? If not it would be nice to have something like:

``` csharp
I.Expect.Count(0).Of("#something").WithoutWait();
// or
I.Expect.WithoutWait().Count(0).Of("#something");
```

**Comment by stirno** [comment]
thats a great point, we'll get something in for 'immediate' expects/asserts into 2.4. Short term that logic could probably be encapsulated in an extension method.

**Comment by vorou** [comment]
I have a somewhat related issue, but I'd like to assert that element is not visible, I ended up with this extension method:

```
public static void ExpectHidden(this INativeActionSyntaxProvider I, string selector)
{
    var element = I.Find(selector)();
    var elementClass = element as Element;
    I.Expect.True(() => elementClass != null && !elementClass.WebElement.Displayed);
}
```

Am I reinventing the wheel, or there is no such a method indeed?

**Comment by stirno** [comment]
@vorou there is no current method that validates something exists but is not displayed... but I'll get it in 3.0 ;)

**Comment by stirno** [comment]
Added for v3.0, in fixmultibrowser branch now.

I.Expect.Not.Exists("#fd");
I.Expect.Not.Visible(“#id”);
I.Expect.Visible(“#id”);
I.Assert.Not.Visible(“#id”);
I.Assert.Visible(“#id”);

Closing this issue and creating a new one for per-assertion waits
