### ISSUE TITLE
Unable to get proxy working

### ISSUE THREAD

**Issue by markhopwood** [stirno/FluentAutomation#85]
Is this the correct way to add a proxy to the dictionary? I can successfully use the proxy when specifying directly in the Selenium remote webdriver capabilities but when I try to do it using the SeleniumWebDriver.Bootstrap the proxy settings appear to be ignored.

public void TestSetup()
{
     var proxy = ConfigureProxySettings(Proxy);
     dictionary.Add("Proxy", proxy);
     SeleniumWebDriver.Bootstrap(uri, SeleniumWebDriver.Browser.Firefox, dictionary);
}
        private static Proxy ConfigureProxySettings(string proxyString)
        {
            Proxy proxy = new Proxy();
            proxy.HttpProxy = 192.168.5.35:8080;
            proxy.SslProxy = 192.168.5.35:8080;
            return proxy;
        }

**Comment by stirno** [comment]
Shooting from the hip here but the way the dictionary gets converted inside Selenium, the Dictionary key has to match the string value of CapabilityType which for Proxy is lowercase 'proxy'.

Try changing it to lowercase and see if it works. If it doesn't I'll take a stab at reproducing it this weekend. Thanks!

**Comment by stirno** [comment]
you can use the full reference to the CapabilityType as the key as well, if you want to avoid your own magic string.. 

```
dictionary.add(OpenQA.Selenium.Remote.CapabilityType.Proxy, proxy);
```

**Comment by stirno** [comment]
Did this function for you with the correct proxy key name @markhopwood?

**Comment by markhopwood** [comment]
Hi, and thanks for the replies. I'm on leave at the moment but I'll be back in the office Thursday morning UK time so will be able to try it out then and will let you know ASAP.

Regards,
Mark

Sent from my HTC

----- Reply message -----

**Comment by markhopwood** [comment]
I've manged to verify this at home. using the fully qualified name works fine, i.e. , dictionary.add(OpenQA.Selenium.Remote.CapabilityType.Proxy, proxy);  Many thanks for the help.

**Comment by stirno** [comment]
No problem, let us know if you have any other issues!
