### ISSUE TITLE
Execute xPath query to find element by text

### ISSUE THREAD

**Issue by lcrodriguez** [stirno/FluentAutomation#86]
It does not seem to be supported, but it's supported in Selenium WebDriver.

Is there any workaround for that feature?
Thanks.

**Comment by lcrodriguez** [comment]
I've just found out that the IDriver is exposed now.

```
        var webDriver = (IWebDriver)this.Provider;
        webDriver.FindElement(By.XPath("//input[@id='userName']")).SendKeys("leo");
```

So seems to be avaiable.

**Comment by stirno** [comment]
As you've noticed we don't use xPath selectors in FluentAutomation currently - The example you used is easily expressible via CSS as:

```
input#username
```

or even just

```
#username
```

If there is enough requests from users for xPath (or we get some spare time in the next few weeks) we'll add them.

Thanks!

**Comment by lcrodriguez** [comment]
Yes but I'm needed to search by an element text and I'm guessing is not supported with CSS.

**Comment by stirno** [comment]
The actual implementation for CSS selectors atm is actually Sizzle (the CSS engine bundled with jQuery). It includes the :contains() selector which can do text matching. -- [https://github.com/jquery/sizzle/wiki/Sizzle-Documentation#wiki--selectors](https://github.com/jquery/sizzle/wiki/Sizzle-Documentation#wiki--selectors) should help there.

Having said that, using the text of an element for locating it can be somewhat fragile. I usually recommend against it where possible.

**Comment by lcrodriguez** [comment]
Thanks for the information.
Great job on this tool!
