### ISSUE TITLE
Use for automation not for testing

### ISSUE THREAD

**Issue by LSTANCZYK** [stirno/FluentAutomation#88]
Hi. 
I would like to use fluent automation to be able to automate user task, not to perform a test. 
I can not figure out how one would achieve that. I want a functionality similar to what scriptcs offers. 

I am trying to automate uploading a sales tax return for the state of South Dakota. Since there is no web API I thought of automating the browser.
I am looking for a fluent automation equivalent of code that just using WatiN looks like this:

```
var browser = new IE();

            browser.GoTo("https://apps.sd.gov/applications/RV23EPath/Login.aspx");
            browser.TextField(Find.BySelector("#ctl00_Content_txtUserName")).Clear();
            browser.TextField(Find.BySelector("#ctl00_Content_txtPassword")).Clear();
            browser.TextField(Find.BySelector("#ctl00_Content_txtUserName")).TypeText(username);
            browser.TextField(Find.BySelector("#ctl00_Content_txtPassword")).TypeText(password);
            browser.Button(Find.BySelector("#ctl00_Content_btnContinue")).Click();
            browser.WaitUntilContainsText("File and/or pay taxes.");
            browser.Link(Find.BySelector("#ctl00_Content_lnkFileReturn")).Click();
```

**Comment by stirno** [comment]
Easiest way to do this is to ignore the word Test. Since you mentioned scriptcs, I recommend you take a look at [http://fluent.stirno.com/fluentautomation-scriptcs/](http://fluent.stirno.com/fluentautomation-scriptcs/). Hell, using scriptcs you can change it to whatever you want!

Below is a sample of something similar to your WatiN code, written with FluentAutomation + scriptcs.

```
var Browser = Require<F14N>().Init<FluentAutomation.SeleniumWebDriver>().Bootstrap("Chrome");

var username = "";
var password = "";

Browser.Run(I => {
    I.Open("https://apps.sd.gov/applications/RV23EPath/Login.aspx");
    I.Enter(username).In("#ctl00_Content_txtUserName");
    I.Enter(password).In("#ctl00_Content_txtPassword");
    I.Click("#ct100_Content_btnContinue");
    I.Expect.Text("File and/or pay taxes.");
    I.Click("#ct100_Content_lnkFileReturn");
});
```

**Comment by LSTANCZYK** [comment]
But I DON'T want to use scriptCS. You say ignore word test. I want to do
this without declaring a test class and then instantiating it and running
the test method. I want the code to resemble the one from scriptcs example
without actually using scriptcs

**Comment by stirno** [comment]
Ok then.. well its all just code. Nothing actually tied to a test framework or anything else.. so just new up a FluentTest class and steal its I property and get to work.

Put this inside any block of C# with the proper references to FluentAutomation.SeleniumWebDriver:

```
SeleniumWebDriver.Bootstrap(SeleniumWebDriver.Browser.Chrome);
var I = new FluentTest().I;

var username = "";
var password = "";

I.Open("https://apps.sd.gov/applications/RV23EPath/Login.aspx");
I.Enter(username).In("#ctl00_Content_txtUserName");
I.Enter(password).In("#ctl00_Content_txtPassword");
I.Click("#ct100_Content_btnContinue");
I.Expect.Text("File and/or pay taxes.");
I.Click("#ct100_Content_lnkFileReturn");
```

**Comment by LSTANCZYK** [comment]
And that's what I thought, but it did not want wo work for me. I will Gove
it another try on monday. thx

**Comment by stirno** [comment]
Cool, if you have any issues, throw up a gist of your code and I'll try and repro. Have a good weekend!

**Comment by stirno** [comment]
Did this end up working out for you @LSTANCZYK?

**Comment by stirno** [comment]
Closing assuming all is good given no updates for a few weeks. Thanks!
